// Registers the service worker and shows a small badge while the site is
// being saved for offline use, then "Ready offline" for a few seconds.
// Generated by site-offline-kit. Progress is read straight from the cache,
// so it also works on pages just outside the worker's scope (Webflow Cloud
// serves an app's home page at "/app" while the scope is "/app/").
(function () {
  if (!('serviceWorker' in navigator) || !window.caches) return;
  // sw.js and precache.json sit next to this script.
  var here = (document.currentScript && document.currentScript.src) || location.href;
  var swUrl = new URL('sw.js', here).href;
  var listUrl = new URL('precache.json', here).href;

  var badge;
  function show(text, done) {
    if (!badge) {
      badge = document.createElement('div');
      badge.style.cssText =
        'position:fixed;left:12px;bottom:12px;z-index:2147483647;padding:8px 12px;' +
        'border-radius:8px;font:500 13px/1.2 -apple-system,system-ui,sans-serif;' +
        'color:#fff;background:rgba(20,20,20,.85);pointer-events:none;transition:opacity .4s';
      document.body.appendChild(badge);
    }
    badge.textContent = text;
    badge.style.opacity = '1';
    if (done) setTimeout(function () { badge.style.opacity = '0'; }, 4000);
  }

  function shownOnce() {
    try {
      if (sessionStorage.getItem('offline-ready-shown')) return true;
      sessionStorage.setItem('offline-ready-shown', '1');
    } catch (_) {}
    return false;
  }

  async function watch(reg) {
    var list;
    try { list = await (await fetch(listUrl, { cache: 'no-store' })).json(); }
    catch (_) { return; } // offline: the copy is already saved, nothing to report
    var total = list.files.length;
    for (;;) {
      var done = 0;
      if (await caches.has(list.cache)) done = (await (await caches.open(list.cache)).keys()).length;
      var installing = !!(reg.installing || reg.waiting);
      if (done >= total) {
        if (!shownOnce()) show('Ready offline ✓', true);
        return;
      }
      if (!installing && reg.active && done > 0) {
        show('Saved, but ' + (total - done) + ' files failed — reload to retry', true);
        return;
      }
      show('Saving for offline… ' + done + ' / ' + total);
      await new Promise(function (r) { setTimeout(r, 1500); });
    }
  }

  window.addEventListener('load', function () {
    navigator.serviceWorker.register(swUrl).then(watch).catch(function () {});
  });
})();
