// Offline service worker, generated by site-offline-kit (offline_site.py).
// The file list lives in precache.json; APP and VERSION are stamped in at
// build time so browsers notice a new build. Everything is resolved against
// this worker's scope, so it works at a domain root or under a mount path
// (e.g. /app/ on Webflow Cloud).
const APP = '__APP__';
const VERSION = '__VERSION__';
const CACHE = APP + '-' + VERSION;
const CONCURRENCY = 6;
const SCOPE = self.registration.scope; // e.g. "https://host/app/"

// The same file can be requested as "(1)" or "%281%29", "@" or "%40"; use one
// canonical cache key (full URL, no query) so every spelling hits the cache.
// Media may live on a CDN, hence full URLs rather than paths.
function keyFor(u) {
  const url = new URL(u, SCOPE);
  let path = url.pathname;
  try { path = decodeURIComponent(path); } catch (e) {}
  return new URL(path, url.origin).href;
}

// Hosts like Webflow Cloud redirect /app/x.html -> /app/x. A stored
// redirected response can't answer a page navigation, so keep just the body.
function unredirect(res) {
  if (!res.redirected) return res;
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers: res.headers });
}

async function precache() {
  const list = await (await fetch(new URL('precache.json', SCOPE), { cache: 'no-store' })).json();
  const cache = await caches.open(CACHE);
  const files = list.files;
  let i = 0;
  async function worker() {
    while (i < files.length) {
      const url = files[i++];
      try {
        if (!(await cache.match(keyFor(url)))) {
          // CORS mode so CDN files are stored readable (Webflow's CDN allows
          // it), which the video byte-range handling below needs.
          const res = await fetch(url, { mode: 'cors', cache: 'reload' });
          if (res.ok) await cache.put(keyFor(url), unredirect(res));
        }
      } catch (e) { /* offline.js reports the shortfall */ }
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
}

self.addEventListener('install', (event) => {
  event.waitUntil(precache().then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    // Only this app's old versions: other apps on the same domain keep theirs.
    for (const k of await caches.keys()) {
      if (k.startsWith(APP + '-') && k !== CACHE) await caches.delete(k);
    }
    await self.clients.claim();
  })());
});

// Safari asks for <video> in byte ranges and refuses a plain 200 reply,
// so slice the cached file and answer 206 Partial Content.
async function rangeResponse(request, cached) {
  const buf = await cached.arrayBuffer();
  const m = /bytes=(\d*)-(\d*)/.exec(request.headers.get('range'));
  let start = m[1] ? parseInt(m[1], 10) : 0;
  let end = m[2] ? parseInt(m[2], 10) : buf.byteLength - 1;
  if (!m[1] && m[2]) { start = buf.byteLength - parseInt(m[2], 10); end = buf.byteLength - 1; }
  end = Math.min(end, buf.byteLength - 1);
  return new Response(buf.slice(start, end + 1), {
    status: 206,
    statusText: 'Partial Content',
    headers: {
      'Content-Type': cached.headers.get('Content-Type') || 'video/mp4',
      'Content-Range': `bytes ${start}-${end}/${buf.byteLength}`,
      'Content-Length': String(end - start + 1),
      'Accept-Ranges': 'bytes',
    },
  });
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const sameOrigin = url.origin === location.origin;

  // Pages are saved as /about.html; also accept /about and /.
  let key = url.href;
  if (sameOrigin) {
    let path = url.pathname;
    if (path.endsWith('/')) path += 'index.html';
    else if (req.mode === 'navigate' && !/\.[a-z0-9]+$/i.test(path)) path += '.html';
    key = new URL(path, url.origin).href;
  }
  key = keyFor(key);

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(key);
    if (cached) {
      return req.headers.has('range') ? rangeResponse(req, cached) : cached;
    }
    try {
      const res = await fetch(req);
      // Pick up same-origin files not in the list (e.g. .webm) for next time.
      if (sameOrigin && res.status === 200 && !req.headers.has('range')) cache.put(key, unredirect(res.clone()));
      return req.mode === 'navigate' ? unredirect(res) : res;
    } catch (e) {
      if (req.mode === 'navigate') return (await cache.match(keyFor('index.html'))) || Response.error();
      return Response.error();
    }
  })());
});
